### PR TITLE
add opencontainers labels

### PR DESCRIPTION
**Pull request by jetersen**
There are other useful opencontainer labels though image.source will help renovatebot detect release notes for docker image.

Not sure how you release your docker images.

I have had good experience with using https://github.com/crazy-max/ghaction-docker-meta to add labels when building the docker image.

### CODE REVIEW

**Comment by dani-garcia** [comment]
Sounds okay to me, if you want to add other labels like version or build date, I assume you'd have to do it when the images are going to be built, which is here: https://github.com/dani-garcia/bitwarden_rs/blob/master/hooks/build

**Comment by jetersen** [comment]
Should be simple enough: https://github.com/Rexypoo/docker-openssl/blob/642c5e9263b884e679f1d21021aec5d5e0a2d9ee/hooks/build

**Comment by jjlin** [comment]
@jetersen Are you actively working on this? If not, I can put this together pretty quickly.

**Comment by jetersen** [comment]
Feel free to do so

**Comment by BlackDex** [comment]
Should we close this PR in favor of #1314?

**Comment by jetersen** [comment]
just add `fixes #1293` to #1314 pull request description, than it would auto close once that PR is merged.

**Comment by jjlin** [comment]
> just add `fixes #1293` to #1314 pull request description, than it would auto close once that PR is merged.

This isn't documented to work for PRs, but I added it, so I guess we'll see.

**Comment by jetersen** [comment]
an pull request is also an issue in the github api 😉

**Pull request closed without merging**
