### PR TITLE
Add Kubernetes deployment reference

### PR DESCRIPTION
**Pull request by icicimov**
As per our discussion, adding the Kubernetes deployment reference as subsection.

Cheers,
Igor

### CODE REVIEW

**Comment by mprasil** [comment]
For reference, we're talking about discussion [here](https://github.com/mprasil/bitwarden_rs/pull/3).

@icicimov sorry for not being clear there. I think it would be better to actually add some small description and link to the repository in the document rather than just linking to it from the TOC as people generally don't expect TOC to link to different document. (and also is autogenerated) Hope that makes sense.

**Comment by icicimov** [comment]
I'm sorry, it was getting late here and I was too tired. A properly done PR will follow shortly.

**Comment by mprasil** [comment]
That's perfect, just one typo: `bitworden_rs` should be `bitwarden_rs`.

**Comment by dani-garcia** [comment]
Thanks icicimov!

**Pull request merged**
