### PR TITLE
Cargo fmt

### PR DESCRIPTION
**Pull request by RealOrangeOne**
Run `cargo fmt` on the codebase, and add it to CI

### CODE REVIEW

**Review by williamdes — APPROVED** [review]

**Comment by dani-garcia** [comment]
I think we should try to tweak rustfmt's style a bit, for example, this change:
```rust
let steps: i64 = if CONFIG.authenticator_disable_time_drift() { 0 } else { 1 };

let steps: i64 = if CONFIG.authenticator_disable_time_drift() {
    0
} else {
    1
};
```
Looks worse afterwards.

Then sometimes it decides to not split lines at all, like this:
```
let json = json!({"page_content": "admin/login", "version": VERSION, "error": msg, "urlpath": CONFIG.domain_path()});
let json =
    json!({"page_content": "admin/login", "version": VERSION, "error": msg, "urlpath": CONFIG.domain_path()});
```

Which I assume is because of the macro, but i'd rather that change not be done.

There are others too, particularly with long strings as function parameters, where it moves the string to a new line and it barely reduces the width, in those cases it might be better to split the string and escape the newline with \

I don't know if those things are configurable in rustfmt, if they aren't I'll just have to deal with it 😄

**Comment by RealOrangeOne** [comment]
@dani-garcia I've re-applied to updated `master`, and manually reviewed and re-flowed a couple lines manually.

**Comment by BlackDex** [comment]
I did some testing, and i think i have a nice config. The only thing  missing is a new feature so that chains are not being put on one line as we now have a lot of those separated on a new-line, and using fmt now will compress those to one line.

In v2.x they have this, and i see that there is a PR open for a backport of this feature: https://github.com/rust-lang/rustfmt/pull/4782 , which i would really like to see merged, and then we could use that to have it more inline with how our code looks right now.

These is btw my tested settings
```toml
version = "Two"
edition = "2018"
max_width = 225
newline_style = "Unix"
use_small_heuristics = "Off"
struct_lit_single_line = false
overflow_delimited_expr = true
```

**Comment by RealOrangeOne** [comment]
> max_width = 225
Seems excessive?

I'll try running with that config, see what the diff looks like.

**Comment by BlackDex** [comment]
> > max_width = 225
> > Seems excessive?
> 
> I'll try running with that config, see what the diff looks like.

I checked with `wc -L` which files had long lines, and that seems what we are comfortable with now.

**Comment by RealOrangeOne** [comment]
Turns out there's already a `rustfmt.toml` file in the repo, with a length of 120. Given that's a far more sane number, and what the rest of this PR was formatted with, I left it. 225 was making lines far longer than we'd probably want.

**Pull request merged**
