### PR TITLE
Check for data folder on startup

### PR DESCRIPTION
**Pull request by jjlin**
Currently, when starting up for the first time (running standalone, outside of Docker), bitwarden_rs panics when the `openssl` tool isn't able to create `data/rsa_key.pem` due to the `data` dir not existing:
```
[2021-02-26 18:35:01.596][bitwarden_rs][INFO] JWT keys don't exist, checking if OpenSSL is available...
OpenSSL 1.1.1f  31 Mar 2020
[2021-02-26 18:35:01.604][bitwarden_rs][INFO] OpenSSL detected, creating keys...
genrsa: Can't open "data/rsa_key.pem" for writing, No such file or directory
Can't open data/rsa_key.pem for reading, No such file or directory
140549065942336:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:69:fopen('da
ta/rsa_key.pem','r')
140549065942336:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:76:
unable to load Private Key
Can't open data/rsa_key.der for reading, No such file or directory
140120792266048:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:69:fopen('da
ta/rsa_key.der','rb')
140120792266048:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:76:
unable to load Private Key
[2021-02-26 18:35:01.627][bitwarden_rs][ERROR] Error creating keys, exiting...
```
Instead, we should print a more helpful error message telling the user to create the directory:
> Create the data folder and try again.

Or when running in Docker/Podman:
> Verify that your data volume is mounted at the correct location.

### CODE REVIEW

**Review by williamdes — APPROVED** [review]

**Comment by BlackDex** [comment]
I find this a bit mixed. For me this could be an indicator i configured the data directory wrongly instead of having bitwarden creating it for me on a location which i didn't mend it to be.

Having it automatically created is convenient also of course.

**Comment by jjlin** [comment]
Yeah, I could see this being a potential issue for containerized deployments where the data folder ends up getting wiped out when the container is recreated because the user didn't correctly mount their data volume. I guess some alternatives are:

1. Don't auto-create the data folder inside a container, and just give a more specific error message saying that the data folder doesn't exist
2. Never auto-create the data folder, but give the more specific error message

Any preference?

**Comment by BlackDex** [comment]
I think the latter would be best.
It will trigger people to check there settings again and it would not accidentally create a random folder in docker, or any other ephemeral container technology.

**Comment by jjlin** [comment]
Yeah, I agree it would be simplest to just print a better error message.

**Review by williamdes — APPROVED** [review]

**Pull request merged**
