### PR TITLE
Added reqwest proxy support

### PR DESCRIPTION
**Pull request by BlackDex**
As requested in issue #570 i added system proxy support.
I have tested this it it works via the proxy by setting the environment variable.
Maybe we can create something to have this set in the environment, but i think that is up to docker it self.

### CODE REVIEW

**Comment by dani-garcia** [comment]
Nice, this shouldn't break anything, unless someome has a misconfigured proxy, but I think we can ignore those cases anyway as something was bound to break sometime.

We should document that you might need to set both the `HTTP_PROXY` and `HTTPS_PROXY` variable in the wiki somewhere too.

**Comment by oguh22** [comment]
Hello,

Is it possible to use HTTP_PROXY env variable for tthee admin/diagnostics page ?

**Comment by BlackDex** [comment]
@oguh22, what isn't working now?
I just tested it and the HTTP_PROXY and HTTPS_PROXY env variables seem to work for me.

**Comment by oguh22** [comment]
@BlackDex ,
uuuhm unfortunatly  not ... it is working fine to get websiite images, on my proxy I can see request going to all differents websites.
When I do to the admin/diagnostics page, I see no logs on my proxy and bitwarden_rs is not able to perform checks

**Pull request merged**
