### PR TITLE
Add "New Device Logged In From" email

### PR DESCRIPTION
**Pull request by vverst**
- Added both templates for the New Device Logged In From email.
- Added `send_new_device_logged_in` email function.
- Moved logic of retrieving or creating device to `get_device` function (Is that ok?). When the device is new an email is sent.

### CODE REVIEW

**Comment by vverst** [comment]
I noticed that it was sending the email before the 2fa check so I moved the email to after the two factor authentication check.

**Comment by dani-garcia** [comment]
Nice! Thanks for your work! Sorry I let this unanswered for some time, I just came back from vacation.

**Comment by vverst** [comment]
Thanks! No problem, hope you had a nice vacation.

**Comment by strikerlulu** [comment]
is there any way to disable this feature ? 
i'm using bitwarden as k8s external secrets provider https://external-secrets.io/main/examples/bitwarden/
and its ending this new device login mail too often, can i disable it for a instance with env variable or for single user ?

**Comment by BlackDex** [comment]
No, there is no option for that, other then to disable SMTP.

Or, somehow let that feature use a fixed appId.
The `appId` is stored in `~/.config/Bitwarden CLI/data.json`

**Pull request merged**
