### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by andrzejwp**
Provide link to cdwv/bitwarden-k8s - helm chart for installing bitwarden_rs inside a Kubernetes cluster

### CODE REVIEW

**Comment by dani-garcia** [comment]
We already have some kubernetes links in the wiki: https://github.com/dani-garcia/bitwarden_rs/wiki/Kubernetes-deployment.

What's the difference between this new one and those?

**Comment by mprasil** [comment]
I think the Readme change is a little bit confusing as it's talking about K8S installation, but the actual code provided is Helm package - not everyone is using Helm with k8s.

Also I have to agree with @dani-garcia that the wiki page is better place for this. Feel free to add your chart under Helm section, we can have multiple charts there no prob.

**Comment by Ornias1993** [comment]
Most users don't run this within kubernetes, the Readme is supposed to be somewhat if a short-and-dirty quickstart guide.

Kubernetes is not something that belongs in a quickstart guide on non-kubernetes-centric project imho.

**Comment by BlackDex** [comment]
This can be closed i think?

**Pull request closed without merging**
