### PR TITLE
Add Github build Action

### PR DESCRIPTION
**Pull request by publicarray**
Sometimes It's nice to have a binary to download

### CODE REVIEW

**Comment by dani-garcia** [comment]
Nice, I thought about integrating this in the past but never had the time to properly look into it.

A couple of comments:

- Travis for example also caches the .cargo directory, not just the target folder, any reason for choosing only that one? The cache example in actions_rs does a bit more https://github.com/actions/cache/blob/master/examples.md#rust---cargo.

- Currently the actions are using what I asume is the latest nightly, is there a way to make it respect the rust-toolchain file? This shouldn't be a major problem as lately we haven't had any problems with broken nightlies but would be good to make the building as reproducible as we can.

- Where do the results of the upload artifact action go? In the releases page or somewhere else?

- Also do you think it would be possible to also build the mysql and postgres versions in the same action? Maybe by running the cargo build and upload artifact actions again with a different name?

**Comment by dani-garcia** [comment]
Okay that seems to solve my questions so far, thanks!

**Comment by publicarray** [comment]
No worries, unfortunately the windows (mysql/postgresql) version does not build successfully yet: https://github.com/publicarray/bitwarden_rs/actions d

**Comment by dani-garcia** [comment]
Yeah Windows is a pain with dependencies, but at least I'm happy with having linux binaries.

Don't know if you saw it already, but the diesel project has azure pipelines running on windows, and it seems to be the same format so maybe it can help:
https://github.com/diesel-rs/diesel/blob/master/azure-pipelines.yml#L132

**Comment by dani-garcia** [comment]
Also not sure if also included in the images, but I sucessfully used [vcpkg](https://github.com/microsoft/vcpkg) in Windows in the past to install OpenSSL libraries, so that could be an option.

**Comment by publicarray** [comment]
Cool thanks for the tips! I'll it try again later.

**Comment by publicarray** [comment]
So I don't have a windows install to use so I was just guessing where things are installed. So far I was not able to build the windows version but I think I've made some improvements to the build process (It's just a single file). If you like them I can send you a new PR https://github.com/publicarray/bitwarden_rs/blob/master/.github/workflows/workspace.yml Someone else will need to implement the windows version sorry.

**Comment by publicarray** [comment]
All someone needs to do is set the following on the windows build and it should work

```yml
env:
        OPENSSL_DIR: C:\Program Files\Path to OpenSSL\
        MYSQLCLIENT_LIB_DIR: C:\Program Files\Path to MySQL\
        PQ_LIB_DIR: C:\Program Files\Path to PostgreSQL\
```

**Comment by dani-garcia** [comment]
Okay yeah, the one file version looks nicer indeed. I'll try later today to dust off my old windows laptop and see it I can get it to work, but no big deal if it doesn't, I assume most people only want the linux binaries. Thanks for your work!

**Pull request merged**
