### PR TITLE
Fix change email when no whitelist is configured

### PR DESCRIPTION
**Pull request by tomuta**
Fixed issue #792

### CODE REVIEW

**Comment by dani-garcia** [comment]
The change seems correct, but I think it would be easier to read as something like:
```rust
 let whitelist_str = self.signups_domains_whitelist();
whitelist_str.is_empty() || whitelist_str.split(',').any(|d| d == e[0])
```

That way it's purpose is more clear, as it basically spells what your code comment says.

**Comment by tomuta** [comment]
But that wouldn't catch a semi-empty list, e.g. ",,"
Is there a way to specify that split should not ever output empty tokens?  Then this would work.

**Comment by dani-garcia** [comment]
You could do something like
```rust
whitelist_str.split(',').filter(|s| !s.is_empty()).any(|d| d == e[0])
```

That said, I'd consider that case to be an invalid configuration, so I don't think it's a big deal if it isn't handled perfectly

**Comment by tomuta** [comment]
Does this look better?

**Comment by dani-garcia** [comment]
Yep, thanks!

**Pull request merged**
