### PR TITLE
Update readme for docker hub

### PR DESCRIPTION
**Pull request by mprasil**
Hi, as per our discussion at #62 this is a PR to merge in the README changes. I think most of the information should be preserved, some of it is moved into separate BUILD.md file.

As for the docker hub side of things, if you're interested, create an account there and let me know, I can add you as collaborator, this should hopefully make things easier in the future. If you're not interested having yet another account in your bitwarden Valut, that's fine, but we need to figure out how can we get in touch to set up build trigger so that the whole thing is automated. (email me at miroslav@prasil.info perhaps?)

### CODE REVIEW

**Comment by dani-garcia** [comment]
Alright, I've created a Docker Hub account, at https://hub.docker.com/u/danigarcia/.

I'll merge this now, thanks.

**Comment by mprasil** [comment]
Added you as a collaborator on the repository. Hopefully you can see the [Build Setting](https://hub.docker.com/r/mprasil/bitwarden/~/settings/automated-builds/) now. If you scroll down, you should see build trigger, just add that as a webhook in the github repo settings and see if you can trigger a build this way. Once that's done, this should trigger a build when there's a git push.

**Comment by mprasil** [comment]
I'm still trying to move the source repository path, so maybe wait a bit until that's done. I'll let you know.

**Comment by mprasil** [comment]
Actually I'm afraid that I can't change the source to your repository as I'm not owner or collaborator here. Can you follow the [steps here](https://github.com/docker/hub-feedback/issues/313#issuecomment-265843090) to try and setup the trigger?

**Comment by dani-garcia** [comment]
I've tried that, but that means creating a new image under my name. I've also tried accessing the build settings for your image but apparently collaborators don't have access to that.

The way I see it is we have three options:
- I'll mark you as collaborator here (I'm fine with it if you are too) and hope that it's enough to change the source repo. Then I'll probably have to set-up the webhook to build on git push and then the image should be automated.
- You continue as before, pulling the changes here to your repo, which should be easier now. This would mean no automation, but this proyect doesn't receive important changes that often, so it woudn't be that problematic.
- I create an automated image under my name, and you modify the README of yours to indicate the users to migrate to the new one. This would require action by the users, but as both images are practically the same, the migration shouldn't be complicated.

**Comment by mprasil** [comment]
Man I'd be honoured to be contributor on this project. If you want to go ahead with this, I'm definitely interested. Let's hope that will be enough to change the source repo. (I think it should be)

If that won't work, then I'd rather do pulls manually.

From my experience changing the Readme doesn't really work to redirect people as most will only see it once and then they just use the image. Case in point is my other bitwarden-ruby image which I created as an test image from one of the forks of the ruby API implementation. It raked in 10k+ downloads in days which definitely surprised me (being an non-automatic build from non-main branch code and all that..) but I had no intentions keeping it alive long-term really. I tried to redirect people in Readme and it just doesn't work. That ruby thing is still being downloaded despite the warning and no updates for long time.. (I plan to eventually remove it which might make some of the users look at the Readme, but at that stage you're essentially breaking people's setup)

**Comment by dani-garcia** [comment]
Alright, I've invited you. Hopefully that's enough to solve the problem. 
You are now officially a collaborator of the proyect! 🎉

**Comment by mprasil** [comment]
:confetti_ball: :fireworks: Yay, I think I should celebrate. :wine_glass: 

But the bad news is I still can't setup the repository to do the automated build. I guess as long as I don't have access to repository settings, it won't give me that option. (It for example adds deploy read-only ssh key, which I definitely can't do here) But no worries I can sync the repo manually for now, now that the readme is merged it's not much work and I can eventually automate the sync.

**Pull request merged**
