### PR TITLE
Add `org.opencontainers` labels to Docker images

### PR DESCRIPTION
**Pull request by jjlin**
Closes #1293

### CODE REVIEW

**Review by jetersen — APPROVED** [review]
LGTM

**Comment by jjlin** [comment]
Closes #1293

**Comment by jetersen** [comment]
you need to add it to the description @jjlin :) 

https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by dani-garcia** [comment]
Thanks @jetersen and @jjlin!

**Comment by jetersen** [comment]
Thanks! It just worked. Renovate picked up all the info.

image

**Pull request merged**
