### PR TITLE
Added command line flags for help and version

### PR DESCRIPTION
**Pull request by zethra**
I added help and version cli flags

Signed-off-by: zethra <benaagoldberg@gmail.com>

### CODE REVIEW

**Comment by dani-garcia** [comment]
Looks good to me, I assume this auto generates the --help flag by itself?
I'd change the short flag of --version to a lowercase v, which I think is the most common option.

**Comment by jjlin** [comment]
`-V` is pretty common too, especially when `-v` is taken for verbose.

**Comment by zethra** [comment]
@dani-garcia Yes, help is auto generated.  As far as the version flag, I was thinking along the same lines as @jjlin but I can change it if you want.

**Comment by dani-garcia** [comment]
Well I don't think we are going to be supporting a verbose flag when we have explicit log level options, so I think it's better to keep them all lowercase for the sake of consistency

**Comment by mqus** [comment]
Regarding the version, wouldn't it be possible to use `env!("CARGO_PKG_VERSION")` as a backup, provided that the version in cargo.toml is kept up-to-date? (It's currently still at 1.0.0 though)

**Comment by dani-garcia** [comment]
It's an option, yeah, but it's another thing to keep track of before a release and if I ever forget to do it the release will end up with an incorrect version, which is worse than no version at all, I'd say.

**Comment by dani-garcia** [comment]
thanks, @zethra!

**Pull request merged**
