### PR TITLE
Allow only bug report issues

### PR DESCRIPTION
**Pull request by jjlin**
Remove templates for other issue types, directing them to the forum instead.

### CODE REVIEW

**Comment by jjlin** [comment]
It would probably be good to have some topic templates on the Discourse forum (https://meta.discourse.org/t/what-are-topic-templates/38295), but I don't think I have permissions to set those up.

**Comment by BlackDex** [comment]
Ill check the templates at the forum and see if i can do that.

**Comment by BlackDex** [comment]
Maybe you can point people to the `Generate support string` at the diagnostics page? That would help us a lot, and sensitive items should be hidden already.

**Comment by BlackDex** [comment]
I'm not able the see this feature with my access rights, or it doesn't work on a mobile. Will check via a normal browser tomorrow, but i think only @dani-garcia has access to that on discourse.

**Comment by jjlin** [comment]
> Maybe you can point people to the `Generate support string` at the diagnostics page? That would help us a lot, and sensitive items should be hidden already.

Added

**Review by BlackDex — APPROVED** [review]

**Comment by BlackDex** [comment]
I hope this helps :)

**Pull request merged**
