### PR TITLE
Read config vars from files

### LINKED ISSUE #1194: Docker Secret on SMTP_PASSWORD
Is it possible to get a docker secret feature on (SMTP_PASSWORD=supersecretpassword) so it's not exposed?

for example: SMTP_PASSWORD_FILE=/run/secrets/supersecretpassword

Thanks!

### PR DESCRIPTION
**Pull request by janost**
Fixes #1194.

This is a better implementation of the change previously posted in #1235.

This change allows the user to read configuration variable values from arbitrary files by using the `_FILE` suffix in environment variables.

### CODE REVIEW

**Comment by dani-garcia** [comment]
Looks good to me, I also mostly agree with @BlackDex said here: https://github.com/dani-garcia/bitwarden_rs/pull/1235#issuecomment-735000791.

Reloading is a nice feature but the main problem is there are some settings that aren't reloadable on the fly, and until rocket async we don't have a way to restart the server itself, so it will mean it will work for some settings and not others.

If a user is loading the config from a file, it probably won't make much sense to let them set the value in the admin page config, because they probably want to control where and how the value is stored. At the same time, that's something they can themselves look for and be careful around it.

Also, maybe in this case we should completely disable the option to see the secrets from the admin page?

We should consider what we are going to do about that before the next release, or at least leave it as an undocumented feature until we have all those corners fleshed out. 

Thanks!

**Comment by ahmaddxb** [comment]
i tried doing this but it didnt work

`    environment:
      - ADMIN_TOKEN_FILE=/run/secrets/vaultwarden_admin_token`

**Comment by BlackDex** [comment]
@ahmaddxb , if you ever used the `/admin` interface to save settings, those env/file items are being overwritten.

**Comment by ahmaddxb** [comment]
I got it work i was missing this, 

```
    secrets:
      - vaultwarden_admin_token
```

**Pull request merged**
